# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mnestix-api.fullname" . }}
  labels:
    {{- include "mnestix-api.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "mnestix-api.selectorLabels" . | nindent 4 }}
