apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mnestix-frontend.fullname" . }}
  labels:
    app: {{ include "mnestix-frontend.name" . }}
    chart: {{ include "mnestix-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mnestix-frontend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "mnestix-frontend.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: mnestix-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: src
              mountPath: /app/src
            - name: public
              mountPath: /app/public
      volumes:
        - name: src
          hostPath:
            path: /app/src
        - name: public
          hostPath:
            path: /app/public
