services:
  mnestix-frontend:
    image: gitlab.xitaso.com:5000/mnes/mnestix-frontend # Using the pipeline image
    container_name: mnestix-frontend
    build:
      context: ../.
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    #     - ./data/logo.svg:/app/public/logo
    environment:
      REGISTRY_API_URL: 'https://aas.my.murrelektronik.de/api/aas-registry'
      DISCOVERY_API_URL: 'https://aas.my.murrelektronik.de/api/discovery'
      AAS_REPO_API_URL: 'https://aas.my.murrelektronik.com/api'
      # MNESTIX_BACKEND_API_URL: 'http://localhost:8089'
      MNESTIX_BACKEND_API_URL: 'https://aasmgmt.aas.my.yacoub.de'
      AD_CLIENT_ID: ${AD_CLIENT_ID}
      AD_TENANT_ID: ${AD_TENANT_ID}
      APPLICATION_ID_URI: 'api://mnestix-test-web-api/'
      AAS_LIST_FEATURE_FLAG: true
      COMPARISON_FEATURE_FLAG: true
      AUTHENTICATION_FEATURE_FLAG: true
      LOCK_TIMESERIES_PERIOD_FEATURE_FLAG: true
      THEME_PRIMARY_COLOR: '#6EF688'
      THEME_SECONDARY_COLOR: '#3DB60F'
      #      THEME_LOGO_MIME_TYPE: 'image/svg+xml'
      THEME_LOGO_URL: '/images/murr-company-logo.png'
