# values.yaml

replicaCount: 1

image:
  repository: mnestix/mnestix-api
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 5064

env:
  # Application Settings
  # API Key:
  CustomerEndpointsSecurity__ApiKey: "" # Provide the actual API key
  # Connection to Repository Service:
  ReverseProxy__Clusters__repoCluster__Destinations__destination1__Address: 'https://aas.my.yacoub.de/api'
  ReverseProxy__Clusters__discoveryCluster__Destinations__destination1__Address: 'https://aas.my.yacoub.de/api/discovery'
  # Features Configuration
  Features__AasRegistryMiddleware: true
  Features__AllowRetrievingAllShellsAndSubmodels: true
  Features__UseAuthentication: false
  Features__UseMongoDbBasedAasIdStorage: true
  # InfluxDB Configuration
  # URL to specify the host and port where InfluxDB is running:
  # ReverseProxy__Clusters__influxCluster__Destinations__destination1__Address: 'http://example/'
  # Token:
  # ReverseProxy__Routes__InfluxRoute__Transforms__1__Set: 'Token '
  # MongoDB Configuration
  BasyxDbConnectionConfiguration__MongoConnectionString: 'mongodb://adminUser:adminPassword@mongodb:27017'
  BasyxDbConnectionConfiguration__DatabaseName: aas-env
  BasyxDbConnectionConfiguration__AasCollectionName: 'aas-repo'
  # BasyxDbConnectionConfiguration__LookupServiceCollectionName: lookupservice
  # Microsoft Authentication and Authorization Configuration:
  AzureAd__Domain: 'my.yacoub.de'
  AzureAd__TenantId: 'd4a311d7-79ce-4521-9fb4-7a556b4f997d'
  AzureAd__ClientId: '25dbf051-5d0d-4f75-b896-d0ced8c2dc45'
  # ASP.NET Core URLs
  ASPNETCORE_URLS: 'http://+:5064'

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: backend-api.my.yacoub.de
      paths:
        - path: /
          pathType: Prefix
  tls: []
